### ISSUE TITLE
ModuleNotFoundError: No module named 'helpers2'

### ISSUE THREAD

**Issue by isarsy** [ntelo007/road_detection_mtl#10]
Thanks for your great work！
when I ran the code unet_mtl.py,I met a problem:
Traceback (most recent call last):
  File "unet_mtl.py", line 11, in <module>
    from helpers2 import define_mtl_loss, define_classes, get_n_classes, define_metrics, define_directory_of_data, get_n_tasks, find_region_files, get_mtl_batch, reverse_mtl_one_hot, visualize_MTL
ModuleNotFoundError: No module named 'helpers2'

Do you know how to  get the  'helpers2' module? I think that it may be a module writen by yourself and you forgot to upload it.

**Comment by ntelo007** [comment]
I will upload the missing files immediately. Thank you for letting me know.
